version: 2
aliases:
  - &install-dependencies
    name: Install Node Dependencies
    command: npm install
  - &test
    name: Test
    command: npm run test
  - &build
    name: Build
    command: npm run build
  - &GCP-auth
    name: GCP Authenticate
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/gcp_authenticate.sh
  - &docker-login
    name: Docker login
    command: |
      docker login -u _json_key --password-stdin https://eu.gcr.io <<< "${DOCKER_PASSWORD}"
  - &docker-build-and-push
    name: Docker build and push
    command: |
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      echo 'export VERSION="$VERSION"' >> $BASH_ENV
      chmod u+x .circleci/docker_build_push.sh
      .circleci/docker_build_push.sh
      chmod u+x .circleci/sentry_upload_sourcemaps.sh
      .circleci/sentry_upload_sourcemaps.sh $CIRCLE_BRANCH-v$VERSION $SENTRY_TOKEN abzu
  - &tag-git-version
    name: Tag git commit with build version and push to github
    command: |
      git config --global user.email "circleci@entur.no"
      git config --global user.name "circleci"
      git tag $VERSION
      git push origin $VERSION
  - &create-image-version
        name: Create new image version and store to env var and as file in workspace
        command: |
          echo "export VERSION=$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)"  >> $BASH_ENV
  - &save-dependency-cache
    paths:
      - node_modules
    key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - &restore-dependency-cache
    name: Restore dependency cache
    keys:
      - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

jobs:
  install:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: *install-dependencies
      - save-cache: *save-dependency-cache
  test:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore-cache: *restore-dependency-cache
      - run: *test
  branch-build:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore-cache: *restore-dependency-cache
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *build
  build:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore-cache: *restore-dependency-cache
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *build
      - run: *create-image-version
      - run: *tag-git-version
      - run: *GCP-auth
      - run: *docker-login
      - run: *docker-build-and-push
workflows:
  version: 2
  install-test-build-deploy:
    jobs:
      - install:
          context: org-carbon
      - test:
          context: org-carbon
          requires:
            - install
      - branch-build:
          context: org-carbon
          requires:
            - test
          filters:
            branches:
              ignore:
              - master
      - build:
          context: global
          requires:
            - test
          filters:
            branches:
              only:
              - master
