env: staging

configMap:
  tiamatBaseUrl: "https://api.staging.entur.io/stop-places/v1/graphql"
  authServerUrl: "https://kc-stage.devstage.entur.io/auth"
  OSMUrl: "https://api-stage.entur.org/map/1.0/{z}/{x}/{y}.png"
  tiamatEnv: "test"
  OTPUrl: "https://api.staging.entur.io/journey-planner/v2/graphql"
  auth0Domain: ror-entur-staging.eu.auth0.com
  auth0ClientId: WrqQUHAVuMS3MbKdGcw91TBFTqLLpnUh
  auth0Audience: https://ror.api.staging.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments
  defaultAuthMethod: kc

ingress:
  enabled: true
  loadBalancerIP: 35.233.47.68
  domainName: .staging.entur.org