apiVersion: v1
appVersion: "0.1.0"
description: NSR (National Stoppalce Register)
name: abzu
version: 0.1.0
keywords:
- abzu
sources:
- https://github.com/entur/abzu
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
