name: Set application in maintenance mode
on: workflow_dispatch
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Copy maintenance mode file
        run: mkdir build && cp public maintenance.html index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENT_ROR_ABZU_DEV }}'
          channelId: live
          projectId: ent-ror-abzu-dev
  deploy_staging:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Copy maintenance mode file
        run: mkdir build && cp public maintenance.html index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENT_ROR_ABZU_TST }}'
          channelId: live
          projectId: ent-ror-abzu-tst
  deploy_prod:
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Copy maintenance mode file
        run: mkdir build && cp public maintenance.html index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENT_ROR_ABZU_PRD }}'
          channelId: live
          projectId: ent-ror-abzu-prd
